### ISSUE TITLE
Fix Timer Mechanics

### ISSUE THREAD

**Issue by BelaReimberg** [COSC481W-2024Winter/Fictionary-Frontend#21]
### Bug
Currently when on the /room URL page, the game states that involve a timer do not correctly parse the amount of time passed or reset their counters when playing a new round of the game.

To reproduce:
* go to https://fictionary-frontend-lut5d.ondigitalocean.app/
* start or join a room
* start the game
* wait for the timer to end on the categories component
* the page will switch to the next game state component
* cycle through the game states until the end of the game, and then restart the round back to the categories component
* the categories component will instantly switch to the next component and then render at the bottom of the page below the current game state component
* the timer will also flash briefly showing that it is counting into the negatives

### Intended Behavior After Fix
The intended behavior which should occur after fixing the bug is that the screen (and it's user interface contents) should stay static and unchanging until the timer or submit button is pressed, taking the user to the next page. The timer should also only be counting down from positive to 0, and then reset back to a positive number again. The timer should never dip into negative numbers.

**Comment by eyu776** [comment]
I'm a little dumb and put the rendering code in the wrong function.
