### ISSUE TITLE
Fix - Continue Button Rendering Bug

### ISSUE THREAD

**Issue by StellarSparks** [COSC481W-2024Winter/Fictionary-Frontend#47]
**Bug:**

The continue buttons on the Results and Scoreboard pages are invisible until they are moused over.

**To Reproduce:**

- Go to: [https://fictionary-frontend-lut5d.ondigitalocean.app/](https://fictionary-frontend-lut5d.ondigitalocean.app/)
- Create a room
- Start a game
- Click the text that reads: "(This should not be visible)" on the category voting page
- Click the "submit" button on the artist view of the drawing page
- Click the "submit" button on the guessing page
- Mouse over the area just below  "Your Score:" until you find the continue button before clicking to see the bug on the round score page
- Mouse over the area below the yellow box until you find the continue button on the scoreboard page

**Intended Behavior After Fix:**

The continue buttons should be set to a light teal color by default so that they are clearly visible on the page.

**Comment by BelaReimberg** [comment]
This issue was resolved with the PR of hunter's UI PBI #30
